---
- name: Create Directory structure
  command: mkdir -p {{download_folder}}
  command: mkdir -p {{java_path}}

- name: Download Java
  get_url: url={{ jdk_tarball_url }}  dest={{ java_archive }} headers="Cookie:' gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'" validate_certs=no owner=root group=root  mode=0655
  register: get_java
- debug:
    msg: "Java was downloaded"  
  when:  get_java|changed

- name: copy files
  copy:
    src: "{{ java_archive }}" 
    dest: "/etc/ansible/roles/apim/files" 

- name: Upadating apt-get cache
  apt: 
    update_cache: yes
  become: yes
  become_method: sudo
 

- name: Unpack archive
  stat: 
   path: /opt/jdk1.8.0_131 
  register: javajdk
- action: shell tar -xzvf /etc/ansible/roles/apim/files -C {{download_folder}}
  when: not javajdk.stat.exists
 
- name: Fix ownership
  file: state=directory path={{java_path}} owner=root group=root recurse=yes


- script: /etc/profile.d/java_home.sh.j2
  environment:
    JAVA_HOME:
      - "{{java_path}}"
    PATH: "{{java_path}}/bin:$PATH"



